BOOKS = {
    "Gn": {"name": "Gênesis", "chapters": 50},
    "Ex": {"name": "Êxodo", "chapters": 40},
    "Lv": {"name": "Levítico", "chapters": 27},
    "Nm": {"name": "Números", "chapters": 36},
    "Dt": {"name": "Deuteronômio", "chapters": 31},
    "Js": {"name": "Josué", "chapters": 22},
    "Jz": {"name": "Juízes", "chapters": 21},
    "Rt": {"name": "Rute", "chapters": 4},
    "1Sm": {"name": "1 Samuel", "chapters": 31},
    "2Sm": {"name": "2 Samuel", "chapters": 24},
    "1Rs": {"name": "1 Reis", "chapters": 22},
    "2Rs": {"name": "2 Reis", "chapters": 25},
    "1Cr": {"name": "1 Crônicas", "chapters": 29},
    "2Cr": {"name": "2 Crônicas", "chapters": 36},
    "Ed": {"name": "Esdras", "chapters": 10},
    "Ne": {"name": "Neemias", "chapters": 13},
    "Es": {"name": "Ester", "chapters": 16},
    "Jb": {"name": "Jó", "chapters": 42},
    "Sl": {"name": "Salmos", "chapters": 150},
    "Pv": {"name": "Provérbios", "chapters": 31},
    "Ec": {"name": "Eclesiastes", "chapters": 12},
    "Ct": {"name": "Cantares", "chapters": 8},
    "Is": {"name": "Isaías", "chapters": 66},
    "Jr": {"name": "Jeremias", "chapters": 52},
    "Lm": {"name": "Lamentações", "chapters": 5},
    "Ez": {"name": "Ezequiel", "chapters": 48},
    "Dn": {"name": "Daniel", "chapters": 12},
    "Os": {"name": "Oséias", "chapters": 16},
    "Jl": {"name": "Joel", "chapters": 3},
    "Am": {"name": "Amós", "chapters": 9},
    "Ob": {"name": "Obadias", "chapters": 1},
    "Jn": {"name": "Jonas", "chapters": 4},
    "Mq": {"name": "Miqueias", "chapters": 7},
    "Na": {"name": "Naum", "chapters": 3},
    "Hc": {"name": "Habacuque", "chapters": 3},
    "Sf": {"name": "Sofonias", "chapters": 3},
    "Ag": {"name": "Ageu", "chapters": 2},
    "Zc": {"name": "Zacarias", "chapters": 14},
    "Ml": {"name": "Malaquias", "chapters": 3},
    "Mt": {"name": "Mateus", "chapters": 28},
    "Mc": {"name": "Marcos", "chapters": 16},
    "Lc": {"name": "Lucas", "chapters": 24},
    "Jo": {"name": "João", "chapters": 21},
    "At": {"name": "Atos", "chapters": 28},
    "Rm": {"name": "Romanos", "chapters": 16},
    "1Co": {"name": "1 Coríntios", "chapters": 16},
    "2Co": {"name": "2 Coríntios", "chapters": 13},
    "Gl": {"name": "Gálatas", "chapters": 6},
    "Ef": {"name": "Efésios", "chapters": 6},
    "Fp": {"name": "Filipenses", "chapters": 5},
    "Cl": {"name": "Colossenses", "chapters": 4},
    "1Ts": {"name": "1 Tessalonicenses", "chapters": 6},
    "2Ts": {"name": "2 Tessalonicenses", "chapters": 3},
    "1Tm": {"name": "1 Timóteo", "chapters": 6},
    "2Tm": {"name": "2 Timóteo", "chapters": 4},
    "Tt": {"name": "Tito", "chapters": 3},
    "Hb": {"name": "Hebreus", "chapters": 13},
    "Tg": {"name": "Tiago", "chapters": 5},
    "Fm": {"name": "Filemon", "chapters": 1},
    "1Pe": {"name": "1 Pedro", "chapters": 5},
    "2Pe": {"name": "2 Pedro", "chapters": 3},
    "1Jo": {"name": "1 João", "chapters": 5},
    "2Jo": {"name": "2 João", "chapters": 3},
    "3Jo": {"name": "3 João", "chapters": 1},
    "Jd": {"name": "Judas", "chapters": 1},
    "Ap": {"name": "Apocalipse", "chapters": 22},
}